<html>
<head>
    <title>try ~ catch</title>
</head>
<body>
    <script>

        // 에러 발생으로 인해 계속 진행되어야 하는 코드가 실행이 안 되는 것을 방지하기 위해
        try {
            conso.log("log message")
        } catch (error) {
            console.log(error)
        } finally {
            console.log("무조건 실행")
        }
        // 예외처리 사용
        console.log("안녕하세요")

        // throw를 사용해 강제로 예외 발생
        var x = ""
        
        try {
            if(x === "") throw "empty"
            var y = x + 3 // x는 string이기 때문에 에러가 발생!
            console.log(y)
        } catch (error) {
            // console.log(error) // throw 뒤의 문자열이 에러 메시지로 뜸
            console.log(`error message : ${error}`)
        } finally {
            console.log("exception 유무와 상관 없이 무조건 실행합니다")
        }

    
    </script>
</body>
</html>